language: c
cache: apt

env:
  - TEMPLATE=arm/qemu
  - TEMPLATE=x86/qemu

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq

# TODO make it template-specific
install:
  - sudo apt-get install -qq gcc-arm-none-eabi
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq qemu qemu-system || true

script:
  - make build-"$TEMPLATE"
  - ./scripts/continuous/run.sh "$TEMPLATE"

notifications:
  slack:
    secure: ATPx+JnB3aMwuyXlJElYv47Z17o5h7rVN2xGOdwKyvuB0HKiGxkUfxAOK37CkLVTZ1i1Jozb1aoDGojTO+zmo4kCfKP3VXRLW9RTVhxt96MlUM0FCRed1bxi1A9rswpaEfWQXpuk9GjUPZOYgSK8D+IV63rhT5F9m4b3Z8WLkr0=
